spring:
  cloud:
    gateway:
      routes:
        - id: Driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/driver/**
          filters:
            - AuthenticationFilter

        - id: participation-service
          uri: lb://PARTICIPATION-SERVICE
          predicates:
            - Path=/participation/**
          filters:
            - AuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**



  application:
   name: GATEWAY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
